[build]
    base = "01-Login"
    command = "printf '{\"domain\":\"%s\", \"clientId\":\"%s\"}' \"${AUTH0_DOMAIN}\" \"${AUTH0_CLIENT_ID}\" > auth_config.json && sed -i 's|src=\"js/|src=\"public/js/|g;s|href=\"/css/|href=\"/public/css/|g;s|src=\"/images/|src=\"/public/images/|g' index.html"
