[build]
    base = "02-Calling-an-API"
    command = "env && printf '{\"domain\":\"%s\", \"clientId\":\"%s\", \"audience\":\"%s\"}' \"${AUTH0_DOMAIN}\" \"${AUTH0_CLIENT_ID}\" \"${AUTH0_AUDIENCE}\" > public/auth_config.json && cp index.html public"
    publish = "public"

[functions]
    directory = "netlify/functions/"
